### PR TITLE
Tensorflow compatible DNN weights

### PR DESCRIPTION
**Pull request by hajohajo**
Tensorflow compatible DNN weights for https://github.com/cms-sw/cmssw/pull/31682

### CODE REVIEW

**Comment by jpata** [comment]
Thanks, I would suggest perhasp creating the file in a folder such as `TrackTfClassifier/SAMPLE_ERA.pb`, where SAMPLE could be some hint for the physics sample where it was trained, ERA would be e.g. 2020 or such. Just to prepare for future iterations.

**Comment by jpata** [comment]
+reconstruction
-needed for https://github.com/cms-sw/cmssw/pull/32128

**Comment by jpata** [comment]
or does this need the test to pass first? sorry, i'm unsure about the procedure for externals. the tests for the main PR  cms-sw/cmssw#32128 passed, using this data PR.

**Comment by smuzaffar** [comment]
no need to test it again here ( as it has been tested via cms-sw/cmssw#32128 ).
So this just adds a new empty file TrackTfClassifier/QCDFlatPU_QCDHighPt_ZEE_DisplacedSUSY_2020.pb , is that correct?

**Comment by smuzaffar** [comment]
@hajohajo , is this correct that newly added file is empty?

**Comment by JanFSchulte** [comment]
@smuzaffar Joona is not around anymore, but the file is not actually empty, but contains a tensor flow network for the DNN track selection.

**Comment by jpata** [comment]
I think the github UI is confused here, the file is not empty: https://github.com/hajohajo/RecoTracker-FinalTrackSelectors/blob/master/TrackTfClassifier/QCDFlatPU_QCDHighPt_ZEE_DisplacedSUSY_2020.pb

**Comment by smuzaffar** [comment]
+externals
ah ok, I was also confused due to https://github.com/cms-data/RecoTracker-FinalTrackSelectors/pull/9/files interface (which shows that its an empty file).

**Comment by smuzaffar** [comment]
@silviodonato , @qliphy as this only adds a new file (which is already tested via cms-sw/cmssw#32128) so I am merging it and will also merge it in cmsdist. Feel free to merge cms-sw/cmssw#32128

**Pull request merged**
