### PR TITLE
New weights retrained with properly flattened QCD samples

### PR DESCRIPTION
**Pull request by hajohajo**
Training done with the new training samples using QCD_Flat_15_7000 with PU50, with a flatter spectrum.

### CODE REVIEW

**Comment by mrodozov** [comment]
assign reconstruction

**Comment by mrodozov** [comment]
Resolve: https://github.com/cms-sw/cmsdist/issues/4681

**Comment by slava77** [comment]
+1

based on the discussion in cms-sw/cmssw#21717  

@mrodozov after merging this, please update cms-sw/cmsdist#4516 
or make a new cmsdist PR for further testing.

**Comment by mrodozov** [comment]
updated

**Pull request merged**
