### PR TITLE
update MkFit DNN

### PR DESCRIPTION
**Pull request by minxiyang**
Update MkFit DNN for the newest update of the MkFit reconstruction: https://github.com/cms-sw/cmssw/pull/36246.

The performance of the new DNN: https://jschulte.web.cern.ch/jschulte/DNN_Nov29th/run3finalv4_TTbar/

The test is ran on the dataset  /RelValTTbar_14TeV/CMSSW_12_1_0_pre5-PU_121X_mcRun3_2021_realistic_v15-v2/GEN-SIM-DIGI-RAW with the CMSSW _12_2_X. The performance of the MkFit DNN on the MkFit tracks is compared to the CKF DNN on the CKF dataset.

### CODE REVIEW

**Comment by mmusich** [comment]
@minxiyang 

> The performance of the new DNN: https://jschulte.web.cern.ch/jschulte/DNN_Nov29th/run3finalv4_TTbar/

do you have also the comparison with the current mkFit + DNN tuning?

**Comment by minxiyang** [comment]
> @minxiyang
> 
> > The performance of the new DNN: https://jschulte.web.cern.ch/jschulte/DNN_Nov29th/run3finalv4_TTbar/
> 
> do you have also the comparison with the current mkFit + DNN tuning?

I don't have have the comparison of this update and the previous mkFIt + DNN tuning yet. Do you want the add a new result of the previous MkFit DNN with the previous MkFit reconstruction on the current comparison? 
https://github.com/cms-sw/cmssw/pull/36285. In here I update the new working point.

**Comment by mmasciov** [comment]
@mmusich, @minxiyang: to clarify, the plots that I have shown in today's [TRK POG presentation](https://indico.cern.ch/event/1098365/#6-mkfit-status-report) already used the updated WPs, with only one difference for pixelLessStep, where we used slightly adjusted cuts wrt. cms-sw/cmssw#36285.
Will reproduce the results with pixelLess WPs as in cms-sw/cmssw#36285, and compare to our adjusted ones.

**Comment by mmasciov** [comment]
> @mmusich, @minxiyang: to clarify, the plots that I have shown in today's [TRK POG presentation](https://indico.cern.ch/event/1098365/#6-mkfit-status-report) already used the updated WPs on top of this updated DNN, with only one difference for pixelLessStep, where we used slightly adjusted cuts wrt. [cms-sw/cmssw#36285](https://github.com/cms-sw/cmssw/pull/36285). Will reproduce the results with pixelLess WPs as in [cms-sw/cmssw#36285](https://github.com/cms-sw/cmssw/pull/36285), and compare to our adjusted ones.

@minxiyang, @mmusich, @slava77:
here are MTV results comparing the WP on top of the updated DNN for pixelLessStep:
https://mmasciovecchio.web.cern.ch/BTV_Nov2021/MTV_TTbarPU50_mkFit_for1220pre3_DNNWP/

Legend:
- Blue = Run3_noMkFit (i.e., CKF);
- Red = last mkFit (as in cms-sw/cmssw#36264) with old DNN;
**- Black = last mkFit with new DNN as in this PR and WPs as in cms-sw/cmssw#36285;
- Orange = same as black, with better tuned WP for pixelLessStep.**
Note: in this context, we mostly care of orange vs. black.

Difference is visible in high-purity tracks: https://mmasciovecchio.web.cern.ch/BTV_Nov2021/MTV_TTbarPU50_mkFit_for1220pre3_DNNWP/plots_highPurity/effandfakePtEtaPhi.pdf
-> Orange allows to retain the same efficiency, while reducing fakes+duplicates (in pixelLessStep).
The only suggested change would be, at https://github.com/cms-sw/cmssw/pull/36285/files#diff-143a81f7a4341ac338a7dabe13c4a49a4510ca142d099ba9960be3fb3b96762fR12: 
`PixelLessStep = cms.vdouble(-0.6, -0.5, -0.4)`
-->
`PixelLessStep = cms.vdouble(-0.60, -0.40, 0.02)`

**Comment by minxiyang** [comment]
> 



> > @mmusich, @minxiyang: to clarify, the plots that I have shown in today's [TRK POG presentation](https://indico.cern.ch/event/1098365/#6-mkfit-status-report) already used the updated WPs on top of this updated DNN, with only one difference for pixelLessStep, where we used slightly adjusted cuts wrt. [cms-sw/cmssw#36285](https://github.com/cms-sw/cmssw/pull/36285). Will reproduce the results with pixelLess WPs as in [cms-sw/cmssw#36285](https://github.com/cms-sw/cmssw/pull/36285), and compare to our adjusted ones.
> 
> @minxiyang, @mmusich, @slava77: here are MTV results comparing the WP on top of the updated DNN for pixelLessStep, in TTbar events with =50 (same as shown in today's [TRK POG presentation](https://indico.cern.ch/event/1098365/#6-mkfit-status-report)): https://mmasciovecchio.web.cern.ch/BTV_Nov2021/MTV_TTbarPU50_mkFit_for1220pre3_DNNWP/
> 
> Legend:
> 
>     * Blue = Run3_noMkFit (i.e., CKF);
> 
>     * Red = last mkFit (as in [Update mkFit for CMSSW_12_2_0_pre3 cms-sw/cmssw#36246](https://github.com/cms-sw/cmssw/pull/36246)) with old DNN;
> 
>     * **Black = last mkFit with new DNN as in this PR and WPs as in [update working point for new DNN cms-sw/cmssw#36285](https://github.com/cms-sw/cmssw/pull/36285)**;
> 
>     * **Orange = same as black, with better tuned WP for pixelLessStep**.
> 
> 
> Note: in this context, we mostly care of **orange vs. black**.
> 
> Difference is visible in high-purity tracks: https://mmasciovecchio.web.cern.ch/BTV_Nov2021/MTV_TTbarPU50_mkFit_for1220pre3_DNNWP/plots_highPurity/effandfakePtEtaPhi.pdf -> Orange allows to retain the same efficiency, while reducing fakes+duplicates (in pixelLessStep). The only suggested change would be, at https://github.com/cms-sw/cmssw/pull/36285/files#diff-143a81f7a4341ac338a7dabe13c4a49a4510ca142d099ba9960be3fb3b96762fR12: `PixelLessStep = cms.vdouble(-0.6, -0.5, -0.4)` --> `PixelLessStep = cms.vdouble(-0.60, -0.40, 0.02)`

Hi Slave, thank you. I update working point.

**Comment by minxiyang** [comment]
> > @mmusich, @minxiyang: to clarify, the plots that I have shown in today's [TRK POG presentation](https://indico.cern.ch/event/1098365/#6-mkfit-status-report) already used the updated WPs on top of this updated DNN, with only one difference for pixelLessStep, where we used slightly adjusted cuts wrt. [cms-sw/cmssw#36285](https://github.com/cms-sw/cmssw/pull/36285). Will reproduce the results with pixelLess WPs as in [cms-sw/cmssw#36285](https://github.com/cms-sw/cmssw/pull/36285), and compare to our adjusted ones.
> 
> @minxiyang, @mmusich, @slava77: here are MTV results comparing the WP on top of the updated DNN for pixelLessStep, in TTbar events with =50 (same as shown in today's [TRK POG presentation](https://indico.cern.ch/event/1098365/#6-mkfit-status-report)): https://mmasciovecchio.web.cern.ch/BTV_Nov2021/MTV_TTbarPU50_mkFit_for1220pre3_DNNWP/
> 
> Legend:
> 
> * Blue = Run3_noMkFit (i.e., CKF);
> * Red = last mkFit (as in [Update mkFit for CMSSW_12_2_0_pre3 cms-sw/cmssw#36246](https://github.com/cms-sw/cmssw/pull/36246)) with old DNN;
> * **Black = last mkFit with new DNN as in this PR and WPs as in [update working point for new DNN cms-sw/cmssw#36285](https://github.com/cms-sw/cmssw/pull/36285)**;
> * **Orange = same as black, with better tuned WP for pixelLessStep**.
> 
> Note: in this context, we mostly care of **orange vs. black**.
> 
> Difference is visible in high-purity tracks: https://mmasciovecchio.web.cern.ch/BTV_Nov2021/MTV_TTbarPU50_mkFit_for1220pre3_DNNWP/plots_highPurity/effandfakePtEtaPhi.pdf -> Orange allows to retain the same efficiency, while reducing fakes+duplicates (in pixelLessStep). The only suggested change would be, at https://github.com/cms-sw/cmssw/pull/36285/files#diff-143a81f7a4341ac338a7dabe13c4a49a4510ca142d099ba9960be3fb3b96762fR12: `PixelLessStep = cms.vdouble(-0.6, -0.5, -0.4)` --> `PixelLessStep = cms.vdouble(-0.60, -0.40, 0.02)`

Hi Slava, thanks. I update working point for pixelLess track.

**Comment by slava77** [comment]
+reconstruction

tested with cms-sw/cmssw#36285

**Comment by perrotta** [comment]
+1
- It has to go together with #36285

**Comment by perrotta** [comment]
merge

**Pull request merged**
